jobs_dir: harbor/jobs
debug: true
n_concurrent_trials: 8

tasks:
  - path: harbor/task

agents:
  - name: kimi-sp
    import_path: agents:KimiSp
    model_name: kimi/kimi-for-coding
    skills:
      - https://github.com/obra/superpowers/tree/v6.2.0/skills
    kwargs:
      lifecycle_instruction: Use the `using-superpowers` skill.

  - name: kimi-smol
    import_path: agents:KimiSmol
    model_name: kimi/kimi-for-coding
    skills:
      - ./skills
    kwargs:
      lifecycle_instruction: Use the `smol-activate` skill.

  - name: kimi-mix
    import_path: agents:KimiMix
    model_name: kimi/kimi-for-coding
    skills:
      - ./skills
      - https://github.com/obra/superpowers/tree/v6.2.0/skills/writing-plans
      - https://github.com/obra/superpowers/tree/v6.2.0/skills/test-driven-development
    kwargs:
      lifecycle_instruction: Use the `smol-activate` skill.
